services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ankatech
      MYSQL_USER: ankadev
      MYSQL_PASSWORD: ankadevpass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./back-end
    ports:
      - "3001:3001"
      - "5555:5555"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://ankadev:ankadevpass@db:3306/ankatech
volumes:
  db_data:
